### PR TITLE
use the correct syscall return types

### PR DESCRIPTION
**Pull request by gnode1**
We got bitten by lseek to the end of 7GB file. I went through the file to check for other calls.

### CODE REVIEW

**Comment by paulpopelka** [comment]
I assume this fixes the problem Sanjay was seeing in his testing?  The one he mentioned on the engineering slack channel.

**Comment by gnode1** [comment]
> I assume this fixes the problem Sanjay was seeing in his testing? The one he mentioned on the engineering slack channel.

Yes. The issue he saw was with sleek. Others I just eyeballed.

**Comment by gnode1** [comment]
> I assume this fixes the problem Sanjay was seeing in his testing? The one he mentioned on the engineering slack channel.

Many syscalls return int, I kept it that way. Uint64 is like a conduit, like void, to be cast accordingly on the other side.

**Review by paulpopelka — COMMENTED** [review]
Seems like km_fs_getcwd() should get this treatment too.
I say this because the length argument to the syscall is a size_t.
I doubt this matters much since path length are never going to be 4gb or greater.

**Pull request merged**
